<?xml version="1.0" encoding="utf-8"?><Database Name="Yuliya.Huzarevich" Class="DС1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WSA-003;Initial Catalog=Yuliya.Huzarevich;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Yuliya_HuzarevichConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Depot" Member="Depots">
    <Type Name="Depot">
      <Column Name="DepotId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepotName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Depot_DrugUnit" Member="DrugUnits" ThisKey="DepotId" OtherKey="DepotId" Type="DrugUnit" />
    </Type>
  </Table>
  <Table Name="dbo.DrugType" Member="DrugTypes">
    <Type Name="DrugType">
      <Column Name="DrugTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DrugTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DrugTypeWeight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="DrugType_DrugUnit" Member="DrugUnits" ThisKey="DrugTypeId" OtherKey="DrugTypeId" Type="DrugUnit" />
    </Type>
  </Table>
  <Table Name="dbo.DrugUnit" Member="DrugUnits">
    <Type Name="DrugUnit">
      <Column Name="DrugUnitId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PickNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepotId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DrugTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Depot_DrugUnit" Member="Depot" ThisKey="DepotId" OtherKey="DepotId" Type="Depot" IsForeignKey="true" />
      <Association Name="DrugType_DrugUnit" Member="DrugType" ThisKey="DrugTypeId" OtherKey="DrugTypeId" Type="DrugType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>